### ISSUE TITLE
Ideas for this Schedule

### ISSUE THREAD

**Issue by ChunHIT** [HITSchedule/HITSchedule#8] opened 2019-07-08 14:30 UTC
I like this Schedule very much !!! , and have some ideas about this software 
some ideas :
1.provide a discussion area , so we can have a place to share our information
2.more subject provided will be very great
3.UI is already very beautiful , maybe we can have a fluency swift beteween different weeks

**Comment by Yuxiang-Wei** [comment] 2019-07-08 14:59
Sorry, because I don't have much time, I may not be able to provide a forum or more subject, I hope someone can help me to do these things in the future. For 3, you can see 
Duplicate of #5 .Thanks for your suggestion.

**Closed** 2019-07-18 16:00 UTC
